# Generated by Django 4.2.7 on 2023-12-10 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 10, 25, 22, 167744, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='substances/', verbose_name='Картинка'),
        ),
    ]
